# Generated by Django 5.2.6 on 2025-09-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(default='default_profile_image.jpg', upload_to='profile_images')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('Adresse', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('sex', models.CharField(choices=[('m', 'M'), ('f', 'F')])),
                ('domaine', models.CharField(max_length=100)),
            ],
        ),
    ]
