# Generated by Django 5.2.6 on 2025-09-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(blank='true', default='default_profile_image.jpg', upload_to='profile_images'),
        ),
    ]
